"""create_dekedata_schema

Revision ID: 3862cc265948
Revises: d550d0ed4826
Create Date: 2025-10-30 12:38:42.879085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3862cc265948'
down_revision: Union[str, None] = 'd550d0ed4826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create schema
    op.execute("CREATE SCHEMA IF NOT EXISTS dekedata AUTHORIZATION CURRENT_USER")

    # Create extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("CREATE EXTENSION IF NOT EXISTS \"citext\"")

    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.CheckConstraint("tier IN ('NHL','AHL','ECHL','Juniors','College','HS','Intl','Other')", name='leagues_tier_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='dekedata'
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.CHAR(length=1), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('shoots', sa.CHAR(length=1), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('height_raw', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('weight_raw', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position IN ('F','D','G')", name='players_position_check'),
    sa.CheckConstraint("shoots IN ('L','R','C')", name='players_shoots_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='dekedata'
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', postgresql.CITEXT(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_year >= start_year', name='seasons_end_year_check'),
    sa.CheckConstraint('start_year >= 1900', name='seasons_start_year_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    schema='dekedata'
    )
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('draft_league', postgresql.CITEXT(), nullable=False),
    sa.Column('probability', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('round_estimate', sa.Integer(), nullable=True),
    sa.Column('team_hints', sa.ARRAY(sa.Text()), nullable=True),
    sa.CheckConstraint('probability >= 0 AND probability <= 100', name='drafts_probability_check'),
    sa.ForeignKeyConstraint(['player_id'], ['dekedata.players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['dekedata.seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'draft_league', name='drafts_unique_key'),
    schema='dekedata'
    )
    op.create_index('ix_drafts_league_probability', 'drafts', ['draft_league', 'probability'], unique=False, schema='dekedata')
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('overall', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('prospect', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('skating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('shot', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('iq', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('compete', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('physical', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('projection_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['dekedata.players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['dekedata.seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', name='scores_player_season_key'),
    schema='dekedata'
    )
    op.create_index('ix_scores_player_season', 'scores', ['player_id', 'season_id'], unique=False, schema='dekedata')
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=True),
    sa.Column('code', postgresql.CITEXT(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['dekedata.leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', name='teams_league_id_name_key'),
    schema='dekedata'
    )
    op.create_table('player_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('split', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('competition_strength', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.CheckConstraint("split IN ('Regular','Playoffs','Exhibition')", name='player_seasons_split_check'),
    sa.ForeignKeyConstraint(['league_id'], ['dekedata.leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['dekedata.players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['dekedata.seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['dekedata.teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', 'league_id', 'split', name='player_seasons_unique_key'),
    schema='dekedata'
    )
    op.create_index('ix_player_seasons_league_season', 'player_seasons', ['league_id', 'season_id'], unique=False, schema='dekedata')
    op.create_index('ix_player_seasons_player_season', 'player_seasons', ['player_id', 'season_id'], unique=False, schema='dekedata')
    op.create_table('goalie_stats',
    sa.Column('player_season_id', sa.UUID(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('l', sa.Integer(), nullable=True),
    sa.Column('otl', sa.Integer(), nullable=True),
    sa.Column('so', sa.Integer(), nullable=True),
    sa.Column('ga', sa.Integer(), nullable=True),
    sa.Column('sa', sa.Integer(), nullable=True),
    sa.Column('sv', sa.Integer(), nullable=True),
    sa.Column('toi_min', sa.Integer(), nullable=True),
    sa.Column('gaa', sa.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('sv_pct', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['player_season_id'], ['dekedata.player_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_season_id'),
    schema='dekedata'
    )
    op.create_table('player_stats',
    sa.Column('player_season_id', sa.UUID(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('g', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), sa.Computed('g + a', ), nullable=True),
    sa.Column('pim', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('sog', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('pp_g', sa.Integer(), nullable=True),
    sa.Column('sh_g', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_season_id'], ['dekedata.player_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_season_id'),
    schema='dekedata'
    )
    # Create trigger functions and triggers

    # Player stats guard trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION dekedata.player_stats_guard() RETURNS trigger AS $$
        BEGIN
          IF (SELECT position
              FROM dekedata.players p
              JOIN dekedata.player_seasons ps ON ps.player_id = p.id
              WHERE ps.id = NEW.player_season_id) = 'G' THEN
            RAISE EXCEPTION 'Goalies cannot have player_stats (skater stats)';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER player_stats_guard_tr
        BEFORE INSERT OR UPDATE ON dekedata.player_stats
        FOR EACH ROW EXECUTE FUNCTION dekedata.player_stats_guard();
    """)

    # Goalie stats guard trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION dekedata.goalie_stats_guard() RETURNS trigger AS $$
        BEGIN
          IF (SELECT position
              FROM dekedata.players p
              JOIN dekedata.player_seasons ps ON ps.player_id = p.id
              WHERE ps.id = NEW.player_season_id) <> 'G' THEN
            RAISE EXCEPTION 'Only goalies can have goalie_stats';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER goalie_stats_guard_tr
        BEFORE INSERT OR UPDATE ON dekedata.goalie_stats
        FOR EACH ROW EXECUTE FUNCTION dekedata.goalie_stats_guard();
    """)

    # Create materialized view for player current affiliation
    op.execute("""
        CREATE MATERIALIZED VIEW dekedata.player_current AS
        SELECT DISTINCT ON (p.id)
          p.id AS player_id,
          ps.season_id,
          ps.team_id,
          ps.league_id
        FROM dekedata.players p
        JOIN dekedata.player_seasons ps ON ps.player_id = p.id
        JOIN dekedata.seasons s ON s.id = ps.season_id
        ORDER BY p.id, s.end_year DESC;
    """)

    op.execute("CREATE INDEX ON dekedata.player_current (player_id)")

    # Create unified analytics view
    op.execute("""
        CREATE OR REPLACE VIEW dekedata.player_season_stats AS
        SELECT
          ps.id            AS player_season_id,
          p.id             AS player_id,
          p.name,
          p.position,
          s.label          AS season,
          l.code           AS league,
          t.name           AS team,
          ps.split,
          -- Skater cols (nullable for goalies)
          ks.gp            AS sk_gp,
          ks.g             AS sk_g,
          ks.a             AS sk_a,
          ks.pts           AS sk_pts,
          ks.pim           AS sk_pim,
          ks.plus_minus    AS sk_plus_minus,
          ks.sog           AS sk_sog,
          ks.hits          AS sk_hits,
          ks.blocks        AS sk_blocks,
          ks.pp_g          AS sk_pp_g,
          ks.sh_g          AS sk_sh_g,
          -- Goalie cols (nullable for skaters)
          gg.gp            AS gk_gp,
          gg.gs            AS gk_gs,
          gg.w             AS gk_w,
          gg.l             AS gk_l,
          gg.otl           AS gk_otl,
          gg.so            AS gk_so,
          gg.ga            AS gk_ga,
          gg.sa            AS gk_sa,
          gg.sv            AS gk_sv,
          gg.toi_min       AS gk_toi_min,
          gg.gaa           AS gk_gaa,
          gg.sv_pct        AS gk_sv_pct
        FROM dekedata.player_seasons ps
        JOIN dekedata.players p ON p.id = ps.player_id
        JOIN dekedata.seasons s ON s.id = ps.season_id
        JOIN dekedata.leagues l ON l.id = ps.league_id
        LEFT JOIN dekedata.teams t ON t.id = ps.team_id
        LEFT JOIN dekedata.player_stats ks ON ks.player_season_id = ps.id
        LEFT JOIN dekedata.goalie_stats gg ON gg.player_season_id = ps.id;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop views and triggers
    op.execute("DROP VIEW IF EXISTS dekedata.player_season_stats")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS dekedata.player_current")
    op.execute("DROP TRIGGER IF EXISTS goalie_stats_guard_tr ON dekedata.goalie_stats")
    op.execute("DROP FUNCTION IF EXISTS dekedata.goalie_stats_guard()")
    op.execute("DROP TRIGGER IF EXISTS player_stats_guard_tr ON dekedata.player_stats")
    op.execute("DROP FUNCTION IF EXISTS dekedata.player_stats_guard()")

    # Drop tables
    op.drop_table('player_stats', schema='dekedata')
    op.drop_table('goalie_stats', schema='dekedata')
    op.drop_index('ix_player_seasons_player_season', table_name='player_seasons', schema='dekedata')
    op.drop_index('ix_player_seasons_league_season', table_name='player_seasons', schema='dekedata')
    op.drop_table('player_seasons', schema='dekedata')
    op.drop_table('teams', schema='dekedata')
    op.drop_index('ix_scores_player_season', table_name='scores', schema='dekedata')
    op.drop_table('scores', schema='dekedata')
    op.drop_index('ix_drafts_league_probability', table_name='drafts', schema='dekedata')
    op.drop_table('drafts', schema='dekedata')
    op.drop_table('seasons', schema='dekedata')
    op.drop_table('players', schema='dekedata')
    op.drop_table('leagues', schema='dekedata')

    # Drop schema
    op.execute("DROP SCHEMA IF EXISTS dekedata CASCADE")

    # ### end Alembic commands ###
