"""initial schema from existing database

Revision ID: d550d0ed4826
Revises: 
Create Date: 2025-10-30 12:07:50.309965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd550d0ed4826'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    op.drop_table('leagues')
    op.drop_table('teams')
    op.drop_table('team_members')
    op.drop_table('invitations')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name='invitations_invited_by_users_id_fk'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='invitations_team_id_teams_id_fk'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_table('team_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_members_team_id_teams_id_fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='team_members_user_id_users_id_fk'),
    sa.PrimaryKeyConstraint('id', name='team_members_pkey')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    sa.UniqueConstraint('stripe_customer_id', name='teams_stripe_customer_id_unique'),
    sa.UniqueConstraint('stripe_subscription_id', name='teams_stripe_subscription_id_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('league_status', sa.VARCHAR(length=20), server_default=sa.text("'inactive'::character varying"), autoincrement=False, nullable=False),
    sa.Column('hub_status', sa.VARCHAR(length=20), server_default=sa.text("'inactive'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='leagues_pkey'),
    sa.UniqueConstraint('value', name='leagues_value_unique')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='activity_logs_team_id_teams_id_fk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activity_logs_user_id_users_id_fk'),
    sa.PrimaryKeyConstraint('id', name='activity_logs_pkey')
    )
    # ### end Alembic commands ###
